### ISSUE TITLE
The final upload endpoint seems to have changed?

### ISSUE THREAD

**Issue by Pxmme** [546200350/TikTokUploder#80]
Hey y'all,

I noticed that this is now the POST request being made when uploading a video manually (final step):

```
POST /api/v1/item/create/?app_name=tiktok_web&channel=tiktok_web&device_platform=web&aid=1988&msToken=REDACTED&X-Bogus=REDACTED&_signature=REDACTED HTTP/2
Host: www.tiktok.com
Cookie: REDACTED
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0
Accept: application/json, text/plain, */*
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Content-Type: application/json
Content-Length: 334
Referer: https://www.tiktok.com/creator
Tt-Csrf-Token: REDACTED
X-Secsdk-Csrf-Token: DOWNGRADE
REDACTED-F: REDACTED
REDACTED-B: REDACTED
REDACTED-C: REDACTED
REDACTED-D: REDACTED
REDACTED-Z: q
REDACTED-A: REDACTED
Origin: https://www.tiktok.com
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Te: trailers

{"creation_id":"REDACTED","video_id":"REDACTED","visibility_type":0,"poster_delay":5.09,"text":"fichier","text_extra":[],"markup_text":"fichier","allow_comment":1,"allow_duet":1,"allow_stitch":1,"sound_exemption":0,"geofencing_regions":[],"anchors":[],"tcm_params":"{\"commerce_toggle_info\":{}}"}
```

As compared with the JSON structure being used in the uploader.py script in this Github, we can see that the JSON structure is not the same:

![image](https://github.com/546200350/TikTokUploder/assets/22918318/9b9ad154-06dc-4f63-af6a-bffaadac8dd9)

We can also see in the code that the final POST request is being made to a different endpoint: `/api/v1/web/project/post/`

I think we might need to update the uploader.py script so that it uses the new way of sending this data, to the new endpoint. For now, we seem to be using the old one.

I think this is causing 3 misbehaviors:

- TikTok detects that we are using the old endpoint and the old way of uploading which can lead to 0 views videos & shadowban
- Modifying the value of the `allow_duet` paramater or the `allow_stitch` parameter in the uploader.py script does not work when the video gets uploaded, duets and stitches are still not allowed
- The animated thumbnails are not working for the videos being uploaded with this script, as opposed to videos uploaded manually (upload a video manually then go on your profile on the mobile app and you'll see that you have animated thumbnails, probably because of the `poster_delay` JSON parameter being used against the correct endpoint and with the correct JSON structure as opposed to what this script does)

Could someone take a look at this and confirm that I am right about all this? If so, I'll try to dig deeper into the code and modify it so it works with the new way of doing things. If I succeed, I'll try to do a PR.

Thanks!

**Comment by 546200350** [comment]
Thanks for your suggestion，I`ll try it latter

**Comment by 546200350** [comment]
I have check the newest api, i have found that their is nothing change in the request params.
maybe whate you find is not the key point .

**Comment by 546200350** [comment]
GOODLUCK

**Comment by Thiencau20** [comment]
@546200350 @Pxmme  hello bros, do you have any update for posting to us account tiktokcdn-us.com, because script is only posting to tiktokcdn.com that cause no animate thumb.

I found that this url  **https://vod-ap-singapore-1.bytevcloudapi.com/** only return location to upload for **tiktokcdn.com**
and this url **https://www.tiktok.com/top/v1** return location for **tiktokcdn-us.com**

when I change url for getting tiktokcdn-us.com like this one below I got error **SignatureDoesNotMatch** , I think something request in param is wrong cause that error, like that s=**5fpzqq4qa77** below it random after each request while in script it stick
https://www.tiktok.com/top/v1?Action=ApplyUploadInner&Version=2020-11-19&SpaceName=tiktok&FileType=video&IsInner=1&FileSize=10052716&s=**5fpzqq4qa77**

{'ResponseMetadata': {'RequestId': '20231018044021775B0E986EBA45BF1280', 'Action': 'ApplyUploadInner', 'Version': '2020-11-19', 'Service': 'vod', 'Region': 'US-TTP', 'Error': {'CodeN': 100010, 'Code': 'SignatureDoesNotMatch', 'Message': 'The request signature we calculated does not match the signature you provided. Check your Secret Access Key and signing method. Consult the service documentation for details.'}}}


So my question is how to post request to get the location posting for **tiktokcdn-us.com**. Thank all guys

![screenshot_1697606199](https://github.com/546200350/TikTokUploder/assets/7241067/f5067af1-fe51-4691-890d-d04acada1856)

**Comment by 546200350** [comment]
i`have update the code, you can have try
